name: bluetooth_on_my_body
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.2
  intl: ^0.17.0
  line_icons: ^2.0.1
  mocktail: ^0.3.0
  quick_blue: ^0.5.0-dev.2
  rxdart: ^0.27.5

dev_dependencies:

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    
flutter_intl:
  enabled: true
