name: bluetooth_on_my_body
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  
  flutter_layout_grid: ^2.0.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.2
  intl: ^0.17.0
  line_icons: ^2.0.1
  mocktail: ^0.3.0
  quick_blue: ^0.5.0-dev.2
  rxdart: ^0.27.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo/icons8-bluetooth-1024.png"
  image_path_ios: "assets/logo/icons8-bluetooth-1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo/icons8-bluetooth-1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/icons8-bluetooth-1024.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/logo/

  fonts:
    - family: NotoSansCJKkr
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf

flutter_intl:
  enabled: true
