name: bluetooth_on_my_body
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  firebase_core: ^1.20.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.5+1
  flutter_layout_grid: ^2.0.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.2
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.0-dev.9
  icons_launcher: ^2.0.2
  intl: ^0.17.0
  line_icons: ^2.0.1
  mocktail: ^0.3.0
  quick_blue: ^0.5.0-dev.2

  rolling_switch:
    git:
      url: https://github.com/ska2519/rolling_switch.git
      ref: main
      
  rxdart: ^0.27.5

  string_to_color:
    git:
      url: https://github.com/ska2519/string_to_color.git
      ref: main

dev_dependencies:
  build_runner: ^2.2.0
  flutter_flavorizr: ^2.1.3
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/flutter_gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/logos/

flutter_intl:
  enabled: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "[DEV]Bluetooth On my Body"
      android:
        applicationId: "test.fruitlab.bluetoothOnmyBody"
      ios:
        bundleId: "test.fruitlab.bluetoothOnmyBody"

    prod:
      app:
        name: "Bluetooth On my Body"
      android:
        applicationId: "dev.fruitlab.bluetoothOnmyBody"
      ios:
        bundleId: "dev.fruitlab.bluetoothOnmyBody"