name: bluetooth_on_my_body
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  
  flutter_layout_grid: ^2.0.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.2
  google_fonts: ^3.0.1
  icons_launcher: ^2.0.2
  intl: ^0.17.0
  line_icons: ^2.0.1
  mocktail: ^0.3.0
  quick_blue: ^0.5.0-dev.2
  rxdart: ^0.27.5
  string_to_color:
    git:
      url: https://github.com/hiranthaR/string_to_color.git
      # url: git://github.com/flutter/plugin1.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


icons_launcher:
  image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
  platforms:
    android:
      enable: true
      # image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
      # adaptive_background_color: '#ffffff'
      # adaptive_background_image: 'assets/ic_background.png'
      # adaptive_foreground_image: 'assets/ic_foreground.png'
      # adaptive_round_image: 'assets/ic_logos_round.png'
    ios:
      enable: true
      # image_path: 'assets/logos/icons8_bluetooth_993_1024_whit.png'
    web:
      enable: true
      # image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
      # favicon_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
    macos:
      enable: true
      # image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
    windows:
      enable: true
      # image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
    linux:
      enable: true
      # image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'





flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/logos/

  fonts:
    - family: NotoSansCJKkr
      fonts:
        - asset: assets/fonts/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR-Regular.otf

flutter_intl:
  enabled: true
