name: scan_bluetooth
description: Bluetooth Scanner
publish_to: 'none'

version: 1.1.1+27

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  adaptive_breakpoints: ^0.1.4
  badges: ^2.0.3
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.0.5
  crypto: ^3.0.1
  desktop_window: ^0.4.0
  dual_screen: ^1.0.3
  duration: ^3.0.11
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_database: ^10.0.6
  firebase_dynamic_links: ^5.0.6
  firebase_storage: ^11.0.6
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_layout_grid: ^2.0.1

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.0+1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  go_router: ^5.1.10
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  google_sign_in: ^5.4.2
  hooks_riverpod: ^2.0.2
  icons_launcher: ^2.0.3
  image_picker: ^0.8.6
  in_app_purchase: ^3.0.8
  intl: ^0.17.0
  json_annotation: ^4.7.0
  line_icons: ^2.0.1
  loading_animation_widget: ^1.2.0+3
  logger: ^1.1.0
  mocktail: ^0.3.0
  numeral: ^2.0.1
  package_info_plus: ^1.4.2
  page_flip_builder: ^0.1.3
  permission_handler: ^10.0.0
  quick_blue: ^0.5.0-dev.2
  riverpod_annotation: ^1.0.6
  rxdart: ^0.27.5

  share_plus: ^4.5.3
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.1.0
  string_to_color:
    git:
      url: https://github.com/ska2519/string_to_color.git
      ref: main
  time: ^2.1.1
  timeago: ^3.3.0
  username_gen: ^1.0.4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_flavorizr: ^2.1.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.2
  riverpod_generator: ^1.0.6

flutter_gen:
  output: lib/generated/flutter_gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/logo/
    - assets/image/

  fonts:
    - family:  CustomFlutterIcon
      fonts:
        - asset: lib/src/flutter_icons/fonts/CustomFlutterIcon.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/bomb_1024.png
  android: true
  ios: true
  web: true
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  web_image_mode: center

flutter_intl:
  enabled: true

icons_launcher:
  image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
  platforms:
    android:
      enable: false
    ios:
      enable: false
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
      
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "DEV_BOMB"
        icon: "assets/logo/bomb_1024.png"

      android:
        applicationId: "dev.fruitshop.bomb"
        firebase:
          config: "android/app/src/dev/google-services.json"

      ios:
        bundleId: "dev.fruitshop.bomb"
        icon: "assets/logo/bomb_ios_1024.jpg"
        firebase:
          config: "ios/Runner/dev/GoogleService-Info.plist"
          

    prod:
      app:
        name: "BOMB"
        icon: "assets/logo/bomb_1024.png"

      android:
        applicationId: "app.fruitshop.bomb"
        firebase:
          config: "android/app/src/prod/google-services.json"

      ios:
        bundleId: "app.fruitshop.bomb"
        icon: "assets/logo/bomb_ios_1024.jpg"
        firebase:
          config: "ios/Runner/prod/GoogleService-Info.plist"