name: bluetooth_on_my_body
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  desktop_window: ^0.4.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  
  flutter_layout_grid: ^2.0.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.2
  google_fonts: ^3.0.1
  icons_launcher: ^2.0.2
  intl: ^0.17.0
  line_icons: ^2.0.1
  mocktail: ^0.3.0
  quick_blue: ^0.5.0-dev.2
  rxdart: ^0.27.5
  string_to_color:
    git:
      url: https://github.com/hiranthaR/string_to_color.git

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/flutter_gen/
  integrations:
    flutter_svg: true

icons_launcher:
  image_path: 'assets/logos/icons8_bluetooth_993_1024_white.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/logos/

flutter_intl:
  enabled: true
