name: bluetooth_on_my_body
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.2.0
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  go_router: ^4.2.2
  intl: ^0.17.0
  rxdart: ^0.27.5

dev_dependencies:
  mocktail: 0.3.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
