/// Flutter icons CustomFlutterIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomFlutterIcon
///      fonts:
///       - asset: fonts/CustomFlutterIcon.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomFlutterIcon {
  CustomFlutterIcon._();

  static const _kFontFam = 'CustomFlutterIcon';

  static const IconData group = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user_1 = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData user = IconData(0xf007, fontFamily: _kFontFam);
  static const IconData users = IconData(0xf0c0, fontFamily: _kFontFam);
  static const IconData user_circle = IconData(0xf2bd, fontFamily: _kFontFam);
}
